up42/docs

source/up42-blocks/processing/s2-superresolution.rst
Pull Request
============
Add minimum area size warning for S2 superresolution.
- [na] Provided code samples where relevant
=> Add minimum area warning

.github/PULL_REQUEST_TEMPLATE.md, source/up42-blocks/processing/tiling.rst
Pull Request
============
Clarifies behaviour of tiling block and improves text structure.
- [na] Provided code samples where relevant
=> Clarifies behaviour of tiling block

source/going-further/filters.rst, source/up42-blocks/data/index.rst, source/up42-blocks/data/meteomatics.rst
=> Meteomatics

source/conf.py, source/reference/block-manifest.rst, source/reference/capabilities.rst, source/reference/data-transfer.rst, source/reference/glossary.rst
Pull Request
============
> Tracked in JIRA by [UP-4053](https://geoinformationstore.atlassian.net/browse/UP-4053)
Update the reference documentation to reflect the v2 block capabilities.
- [ x] Checked spelling and grammar
- [ x] Provided code samples where relevant
- [ x] Checked the output of `make html` to ensure new content displays correctly
=> Block cap v2 draft

source/reference/capabilities.rst
See above. Also added links to specs for each meta capability
=> Add kml kmz vector formats

source/up42-blocks/data/pleiades-primary.rst
=> Pleiades primary

source/up42-blocks/processing/snap-polarimetric.rst
=> Updtae snap docs to include new options.

source/reference/parameters.rst
Pull Request
============
Clarify integer and number parameter types
- [na] Provided code samples where relevant
=> Add integer type

source/reference/parameters.rst
Pull Request
============
> Tracked in JIRA by [UP-4164](https://geoinformationstore.atlassian.net/browse/UP-4164)
Add the documentation for the `maximum` and `minimum` attributes in case of an `integer` type job parameter.
=> Add documentation for minimum and maximum boundaries

source/up42-blocks/processing/dimap-conversion.rst, source/up42-blocks/processing/index.rst, source/up42-blocks/processing/netcdf-conversion.rst
=> Add docs for dimap and netcdf conversion blocks

source/up42-blocks/processing/dimap-conversion.rst, source/up42-blocks/processing/netcdf-conversion.rst
=> Doc update for NETCDF conversion

source/up42-blocks/data/pleiades-primary.rst
Pull Request
============
Add a warning that the user needs to choose an AOI with a minimum area of 1sqm.
=> Add aoi minimum size criteria

source/up42-blocks/processing/pansharpen.rst
Pull Request
============
Describe the new functionality (clipping) for the pansharpen block
=> Update pansharpen doc to include clipping option.

source/up42-blocks/processing/dimap-conversion.rst, source/up42-blocks/processing/snap-polarimetric.rst
Pull Request
============
Describe the new functionality (clipping) for the Dimap-conversion block plus fixing some wrong description in the snap block doc.
=> Update dimap conversion docs

source/up42-blocks/processing/index.rst, source/up42-blocks/processing/ship-identification.rst, source/up42-blocks/processing/ship_identification.rst
Pull Request
============
Add ship identification documentation
> Tracked in JIRA by [IN-3718](https://geoinformationstore.atlassian.net/browse/UP-3718?atlOrigin=eyJpIjoiMDEwODk0MTVhMTk3NDhmYTlmOGVlOTE4MTRkMDdlODkiLCJwIjoiaiJ9)
- [x ] Checked spelling and grammar
=> Add ship identification documentation

source/up42-blocks/data/ais-hvp.rst, source/up42-blocks/data/index.rst
Pull Request
============
Adds AIS-HVP chapter.
> Tracked in JIRA by [IN-3727](https://geoinformationstore.atlassian.net/browse/UP-3727)
=> Add ais hvp

source/up42-blocks/data/ais-hvt.rst
Pull Request
============
> Tracked in JIRA by [IN-3809](https://geoinformationstore.atlassian.net/browse/UP-3809?atlOrigin=eyJpIjoiM2MzYjZmNDNmM2ZkNGNlZjhjZWQ0MzRiYjI4N2QxNTQiLCJwIjoiaiJ9)
Adds ais HVT chapter.
Will fix block details link and merge when block is going to production.
=> Add ais hvt

source/up42-blocks/data/pleiades-primary.rst
Pull Request
============
Add a sentence to clarify the behavior of clipping.
=> Add a sentence to clarify the behavior of clipping.

source/going-further/filters.rst
Pull Request
============
I forgot to add Sentinel 2 L2A to the filter.rst. This quick PR is related to this.
=> Add s2l2a to filter.rst file.

source/going-further/filters.rst, source/up42-blocks/data/aws-landsat8.rst, source/up42-blocks/data/index.rst
Pull Request
============
> Tracked in JIRA by [UP-3982](https://up42.atlassian.net/browse/UP-3982)
> Paired with @rodrigoalmeida94 
Add documentation for new AWS based landsat8 data block
=> update docs for AWS landsat8 data block

source/index.rst
Pull Request
============
Python SDK sentence fix.
=> Fix typo in python sdk sentence

source/up42-blocks/processing/index.rst, source/up42-blocks/processing/land-cover.rst
Pull Request
============
> Tracked in JIRA by [UP-3971](https://up42.atlassian.net/browse/UP-3971?atlOrigin=eyJpIjoiMGY4NTUzYWVkMDA3NDViMGI2ZTQwNTQzNWZiMTdmMTkiLCJwIjoiaiJ9)
=> Add Beta Land Cover block

source/going-further/filters.rst, source/up42-blocks/data/index.rst, source/up42-blocks/data/openstreetmap.rst
Pull Request
============
> Tracked in JIRA by [up-3300](https://up42.atlassian.net/browse/UP-3300)
Introduce new vector based OSM data block
=> OSM block docs

source/going-further/filters.rst, source/up42-blocks/data/aws-modis.rst, source/up42-blocks/index.rst
=> Added modis to filters.rst

source/going-further/custom-processing-block-dev.rst
=> Fix label reference

source/up42-blocks/data/nextmap-10m.rst, source/up42-blocks/data/nextmap-1m.rst, source/up42-blocks/data/nextmap-5m.rst
Relates to https://github.com/up42/blocks/pull/626
=> Add maximum size warning for NextMap blocks

source/up42-blocks/data/nextmap-10m.rst, source/up42-blocks/data/nextmap-1m.rst, source/up42-blocks/data/nextmap-5m.rst
=> Explain clipping option in the doc.

source/up42-blocks/processing/pleiades-superresolution.rst
Pull Request
============
> Tracked in JIRA by [UP-4752](https://up42.atlassian.net/browse/UP-4752)
=> Add model option to SPOT/Pleiades Super-resolution 

source/reference/glossary.rst
=> Some typo corrections and repairing some broken links

source/up42-blocks/data/dimap-custom.rst, source/up42-blocks/data/geotiff-custom.rst
=> Fixes formatting custom blocks

source/reference/glossary.rst, source/up42-blocks/data/modis.rst, source/up42-blocks/data/pleiades-download.rst, source/up42-blocks/data/pleiades.rst, source/up42-blocks/data/sentinelhub-landsat8.rst, source/up42-blocks/data/sentinelhub-s2.rst, source/up42-blocks/data/sobloo-s1-grd-aoiclipped.rst, source/up42-blocks/data/sobloo-s1-grd.rst, source/up42-blocks/data/sobloo-s1-slc.rst, source/up42-blocks/data/sobloo-s2-l1c-aoiclipped.rst, source/up42-blocks/data/sobloo-s2-l1c.rst, source/up42-blocks/data/sobloo-s3.rst, source/up42-blocks/data/sobloo-s5p.rst, source/up42-blocks/data/spot-download.rst, source/up42-blocks/data/spot.rst, source/up42-blocks/data/weather-ocean-data-forecasts-meteomatics.rst
=> Updating some definitions and additional corrections

source/up42-blocks/data/nextmap-10m.rst, source/up42-blocks/data/nextmap-1m.rst, source/up42-blocks/data/nextmap-5m.rst
Relates to discussion https://up-42.slack.com/archives/CG8H1200N/p1597398132010800
=> Reduce max extent area to 1/4 to account for projection innacuracies

source/up42-blocks/data/pleiades-download.rst, source/up42-blocks/data/spot-download.rst
=> Added AOI limit for PHR and SPOT

source/up42-blocks/data/geotiff-custom.rst, source/up42-blocks/processing/tiling.rst
Pull Request
============
https://up42.atlassian.net/browse/UP-4772
Reflects small update to tiling block behaviour.
=> Update tiling block

source/up42-blocks/data/ais-hvp.rst, source/up42-blocks/data/ais-hvt.rst, source/up42-blocks/data/aws-landsat8.rst, source/up42-blocks/data/aws-modis.rst, source/up42-blocks/data/aws-s2-l2a.rst, source/up42-blocks/data/dimap-custom.rst, source/up42-blocks/data/geotiff-custom.rst, source/up42-blocks/data/modis.rst, source/up42-blocks/data/nextmap-10m.rst, source/up42-blocks/data/nextmap-1m.rst, source/up42-blocks/data/nextmap-5m.rst, source/up42-blocks/data/openstreetmap.rst, source/up42-blocks/data/pleiades-download.rst, source/up42-blocks/data/pleiades-primary.rst, source/up42-blocks/data/pleiades.rst, source/up42-blocks/data/sentinelhub-landsat8.rst, source/up42-blocks/data/sentinelhub-s2.rst, source/up42-blocks/data/sobloo-s1-grd-aoiclipped.rst, source/up42-blocks/data/sobloo-s1-grd.rst, source/up42-blocks/data/sobloo-s1-slc.rst, source/up42-blocks/data/sobloo-s2-l1c-aoiclipped.rst, source/up42-blocks/data/sobloo-s2-l1c.rst, source/up42-blocks/data/sobloo-s3.rst, source/up42-blocks/data/sobloo-s5p.rst, source/up42-blocks/data/spot-download.rst, source/up42-blocks/data/spot.rst, source/up42-blocks/data/weather-ocean-data-forecasts-meteomatics.rst
=> Update links and small corrections

source/up42-blocks/data/dimap-custom.rst, source/up42-blocks/data/geotiff-custom.rst, source/up42-blocks/data/index.rst, source/up42-blocks/data/nextmap-10m.rst, source/up42-blocks/data/nextmap-1m.rst, source/up42-blocks/data/nextmap-5m.rst, source/up42-blocks/data/pleiades-download.rst, source/up42-blocks/processing/crs-conversion.rst, source/up42-blocks/processing/dimap-conversion.rst, source/up42-blocks/processing/kmeans-clustering.rst, source/up42-blocks/processing/land-cover.rst, source/up42-blocks/processing/ndvi.rst, source/up42-blocks/processing/netcdf-conversion.rst, source/up42-blocks/processing/pansharpen.rst, source/up42-blocks/processing/pleiades-superresolution.rst, source/up42-blocks/processing/s2-superresolution.rst, source/up42-blocks/processing/s5p_lvl3.rst, source/up42-blocks/processing/sharpening.rst, source/up42-blocks/processing/ship-identification.rst, source/up42-blocks/processing/snap-polarimetric.rst, source/up42-blocks/processing/tiling.rst, source/up42-blocks/processing/vectorization.rst, source/up42-blocks/processing/zonal-statistics.rst
=> Updated some links and unifying notes for AOI sizes

source/index.rst
=> Added REST API, SDK and console

source/up42-blocks/data/openstreetmap.rst
Pull Request
============
Slightly modified feature. Updated OSM block for better output filenames as well as geometry field in `data.json`
=> update snippet for data.json

source/up42-blocks/processing/up42-countobjects.rst
Pull Request
============
Added marketplace link and added information about parameters.
=> Added marketplace link and parameter description

source/up42-blocks/data/dimap-custom.rst, source/up42-blocks/data/geotiff-custom.rst, source/up42-blocks/data/sobloo-s1-grd-aoiclipped.rst, source/up42-blocks/data/sobloo-s2-l1c-aoiclipped.rst, source/up42-blocks/processing/land-cover.rst
Pull Request
============
In line with our plan to be more explicit about the aoi size limits that the blocks support, here clarifications for the to Sobloo aoiclipped blocks.
=> Clarify aoi limit sobloos1s2

source/going-further/custom-processing-block-dev.rst
Pull Request
============
Added a sentence referring to our data and processing template repo.
=> Add a reference to our data and processing template repos.

source/up42-blocks/data/openstreetmap.rst, source/up42-blocks/processing/snap-polarimetric.rst
Pull Request
============
> Tracked in JIRA by [UP-4612](https://geoinformationstore.atlassian.net/browse/UP-4612)
=> Add generic osm tag

source/going-further/index.rst, source/up42-blocks/processing/export-data-raster.rst, source/up42-blocks/processing/export-data-vector.rst, source/up42-blocks/processing/kmeans-clustering.rst
Pull Request
============
Clarify nodata handling in kmeans block after update to be rolled out soon and fix some minor issues.
=> Clarify kmeans nodata

source/up42-blocks/processing/land-cover.rst
Pull Request
============
> Tracked in JIRA by [UP-4585](https://up42.atlassian.net/browse/UP-4585)
This PR contains recent changes made into LandCover block to be able to handle 4 or 5 classes for classefication.
=> update landcover documentation

source/up42-blocks/data/airbus-globalseeps-sample.rst, source/up42-blocks/data/index.rst
Pull Request
============
> Tracked in JIRA by [UP-4896](https://geoinformationstore.atlassian.net/browse/UP-4896)
=> Add Airbus Global Seeps Sample docs

source/up42-blocks/processing/s2-superresolution.rst
Pull Request
============
Add support for L1C and L2A.
=> Update S2 superres

source/up42-blocks/processing/index.rst, source/up42-blocks/processing/oneatlas-cloudmask.rst
Pull Request
============
> Tracked in JIRA by https://up42.atlassian.net/browse/UP-4837?atlOrigin=eyJpIjoiMzkwZWNhZjk0MjBkNDVkMjg3MWJkMzRjMGVhODk2NmYiLCJwIjoiaiJ9
New chapter describing OneAtlas cloud mask processing block.
=> Cloud masking docs

source/up42-blocks/processing/s5p_lvl3.rst
=> add resolution parameter

source/FAQ/api.rst, source/reference/api-usage-constraints.rst, source/reference/index.rst
Pull Request
============
Add a section about the API usage constraints.
- [ x] Checked spelling and grammar
- [ x] Provided code samples where relevant
- [ x] Checked the output of `make html` to ensure new content displays correctly
=> * Add API usage constraints section.

source/up42-blocks/data/pleiades-primary.rst
Pull Request
============
> Tracked in JIRA by [UP-5029](https://geoinformationstore.atlassian.net/browse/UP-5029)
- [na] Provided code samples where relevant
=> Add warning for up42.data_path in Pleiades Primary

source/going-further/filters.rst, source/up42-blocks/data/index.rst, source/up42-blocks/data/pleiades-display.rst, source/up42-blocks/data/spot-display.rst
Pull Request
============
> Tracked in JIRA by https://up42.atlassian.net/browse/UP-5008?atlOrigin=eyJpIjoiZjMzNjFhZjNmMDY1NDgwN2I3MDgzZTc3MTk5ZjUyYTIiLCJwIjoiaiJ9
Documentation for OneAtlas Pleiades and SPOT Display products.
=> Oa display documentation

source/getting-started/demo-workflow.rst, source/getting-started/first-workflow.rst
=> Fixed hyperlinks

source/getting-started/catalog-search.rst, source/getting-started/index.rst, source/getting-started/video-tutorials.rst, source/going-further/download-blocks-tutorial-spot-pleiades.rst, source/index.rst
Pull Request
============
To add a section on the possible paths for exploring UP42 based on the customer profile.
=> * Added UP42 paths to the docs.

source/up42-blocks/data/sentinelhub-landsat8.rst, source/up42-blocks/data/sentinelhub-s2.rst
Pull Request
============
Adds cloud cover to sentinelhub blocks, see https://github.com/up42/blocks/pull/795
=> add cc parameters to sentinelhub blocks

source/getting-started/first-workflow.rst, source/going-further/core-concepts.rst, source/going-further/download-blocks-tutorial-spot-pleiades.rst, source/up42-blocks/data/pleiades-display-download.rst, source/up42-blocks/data/pleiades-reflectance-download.rst, source/up42-blocks/data/spot-display-download.rst, source/up42-blocks/data/spot-reflectance-download.rst
Pull Request
============
> Tracked in JIRA by [IN-5106](https://geoinformationstore.atlassian.net/browse/IN-5106)
Remove mentions of order_ids. Add asset_id.
=> Add asset id OneAtlas up5106

source/going-further/filters.rst, source/up42-blocks/data/index.rst, source/up42-blocks/data/meteomatics-weather-map.rst
Pull Request
============
Add documentation for Meteomtaics WMS based weather map.
Need to update the query and their responses and also add the correct link!
=> Add meteomatics weather map docs.

README.md, requirements.txt, screenshots/resource.robot, screenshots/valid_login.robot
Pull Request
============
Fix robot screenshots functionality.
=> Update robot settings to working version

source/up42-blocks/processing/index.rst, source/up42-blocks/processing/up42-terrasar-geotiff-conversion.rst
Pull Request
============
> Tracked in JIRA by [UP-4918](https://console.up42.com/projects/2aa6bb18-ff42-4d3b-8776-fa3d4946c78d/jobs/45c70dd2-b73b-43d4-b1b9-58daf2e724fd?workspace=73bdbb90-c2c8-4432-90dc-80b5644cbeac)
Adds TSX Conversion chapter.
=> Add tsx conversion

source/up42-blocks/data/index.rst, source/up42-blocks/data/up42-import-geojson.rst
Pull Request
============
Adding docs for new Import Data (GeoJSON).
=> Add import geojson data first draft

source/up42-blocks/processing/land-cover.rst
Pull Request
============
> Tracked in JIRA by [UP-5123](https://up42.atlassian.net/browse/UP-5123)
=> update lc docs

source/up42-blocks/processing/vectorization.rst
Pull Request
============
> Tracked in JIRA by [IN-XXX](https://geoinformationstore.atlassian.net/browse/IN-5131)
=> Add max size warning for vectorisation

source/going-further/download-blocks-tutorial-spot-pleiades.rst
=> info streamed vs downloaded

source/up42-blocks/processing/up42-ndvithreshold.rst
Pull Request
============
This PR updates the ndvi-thresholding block url. thanks to @thaisbendixen for finding this out!
=> Update the url to refer to prod

source/going-further/download-blocks-tutorial-spot-pleiades.rst
=> add disclaimer for streaming

source/up42-blocks/processing/index.rst, source/up42-blocks/processing/up42-floodfinder.rst, source/up42-blocks/processing/up42-waterfinder.rst
Pull Request
============
> Tracked in JIRA https://up42.atlassian.net/browse/UP-4994
Documentation for new waterfinder and floodfinder blocks.
The Waterfinder block outputs a water mask for Pleiades and SPOT imagery.
The Floodfinder block outputs a floodmask for Pleiades and SPOT imagery from on a minimum of two input images.
=> Documentation for Waterfinder and Floodfinder Blocks

source/up42-blocks/data/airbus-globalseeps.rst, source/up42-blocks/data/index.rst
Pull Request
============
> Tracked in JIRA by [UP-5115](https://geoinformationstore.atlassian.net/browse/UP-5115)
Add Global Seeps documentation.
=> Add Global Seeps

source/up42-blocks/data/meteomatics-weather-map.rst
=> fixed meteomatics link

source/getting-started/sign-up.rst
=> added signup credits

source/up42-blocks/data/dimap-custom.rst, source/up42-blocks/data/geotiff-custom.rst, source/up42-blocks/data/up42-import-geojson.rst, source/up42-blocks/processing/export-data-raster.rst, source/up42-blocks/processing/export-data-vector.rst
Pull Request
============
Adds info that no AWS region setting is required.
See https://github.com/up42/blocks/pull/870
=> describe aws region env variable

source/up42-blocks/data/sobloo-s1-slc.rst
Pull Request
============
This PR adds two extra params to the s1slc params description.
=> Update s1slc docs to include two new params

source/FAQ/pricing.rst
=> 24 months expiry

source/FAQ/general.rst
=> update general FAQs

source/FAQ/console.rst, source/FAQ/general.rst, source/getting-started/sign-up.rst
=> updated FAQs

source/up42-blocks/processing/land-cover.rst
Pull Request
============
Petite PR for removing beta version from tite and description
=> remove beta version from lc docs

source/going-further/filters.rst, source/up42-blocks/data/esa-s5p-l3-gtiff.rst, source/up42-blocks/data/index.rst
Pull Request
============
> Tracked in JIRA by [UP-5221](https://up42.atlassian.net/browse/UP-5221)
> Paired with @nekhtiari 
The scope of PR is to submit documentation for new Sentinel-5p level-3 block.
**NOTE:**
Currently, the block is not published on production, therefore the marketplace url is incorrect. Once the block goes to prod, will update with the correct URL.
=> add s5p data block documentation

source/up42-blocks/data/weather-ocean-data-forecasts-meteomatics.rst
Pull Request
============
Add hints to AOI size for meteomatcis block.
=> Add hint for AOI size

source/FAQ/compliance.rst, source/up42-blocks/data/exactearth-ais-query-vessel.rst, source/up42-blocks/data/pleiades-primary.rst
=> updates and corrections

source/going-further/filters.rst
=> Replace results with images

source/getting-started/first-api-request.rst
=> Removing the extra the

source/going-further/api-walkthrough.rst
=> Reviewing and making changes to API Walkthrough (Round 1)

source/going-further/filters.rst, source/up42-blocks/data/index.rst, source/up42-blocks/data/oneatlas-worlddem-12m.rst
Pull Request
============
Add documentation for WorldDEM 12m data block.
=> Add worlddem docs

source/up42-blocks/data/oneatlas-worlddem-12m.rst
Pull Request
============
Added forgotten prod link to the doc.
=> Add prod link

source/specs/openapi.yaml
=> add api endpoints

source/FAQ/general.rst
=> Content addition and removal in FAQs

source/up42-blocks/data/meteomatics-agriculture.rst, source/up42-blocks/data/meteomatics-energy.rst, source/up42-blocks/data/meteomatics-ocean.rst
=> Update names meteomatics

source/going-further/custom-processing-block-dev.rst
Pull Request
============
Added 'cat' to the docker build code in the documentation.
=> added 'cat' to the docker build code in the documentation

source/up42-blocks/processing/pansharpen.rst
Pull Request
============
> Tracked in JIRA by https://up42.atlassian.net/browse/UP-5410?atlOrigin=eyJpIjoiMmY0MDE0YTI2NGNmNGM1MDg4Y2YyN2U2MWM4MjUwNTMiLCJwIjoiaiJ9
This PR adds information about new compatibility of the Pansharpening Block with S2 Analytic Block.
=> Update pansharpen doc with s2 compatibility

source/going-further/filters.rst
=> Fixed OneAtlas links and naming in Data Source Query Filters
